language: C
compiler: gcc

script:
  - gcc -coverage -I ./include -I ./include/utils test/src/buddy.test.c src/*.c src/utils/*.c -o buddy -lm
  - gcov buddy
  - ./buddy
  - bash <(curl -s https://codecov.io/bash)
  - gcc -coverage -I ./include -I ./include/utils test/src/map.test.c src/*.c src/utils/*.c -o map -lm
  - gcov map
  - ./map
  - gcc -coverage -I ./include -I ./include/utils test/src/stack.test.c src/*.c src/utils/*.c -o stack -lm
  - gcov stack
  - ./stack
  - gcc -coverage -I ./include -I ./include/utils test/src/utils.test.c src/*.c src/utils/*.c -o utils -lm
  - gcov utils
  - ./utils

after_success:
  - bash <(curl -s https://codecov.io/bash)

